-- ==========================================
-- SCRIPT DE MIGRACIÓN SUPABASE: INVENTARIO KARINA
-- ==========================================
-- Instrucciones: Entra a Supabase -> SQL Editor -> New Query. 
-- Pega absolutamente todo este texto ahí y presiona "RUN" (Aceptar).

CREATE TABLE public.products (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  marca TEXT,
  codigo TEXT,
  descripcion TEXT,
  is_active INTEGER DEFAULT 1,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE public.transactions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  product_id BIGINT REFERENCES public.products(id) ON DELETE CASCADE,
  type TEXT,
  quantity NUMERIC,
  date TEXT,
  costo_unitario NUMERIC,
  total_bolivares NUMERIC,
  factura TEXT,
  destino TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- SEGURIDAD AVANZADA (RLS)
-- Esto prohibe terminantemente que cualquier atacante con la URL pueda leer o escribir datos si no ha iniciado sesión.
ALTER TABLE public.products ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.transactions ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Proteccion Lectura Productos Logueados" ON public.products FOR ALL TO authenticated USING (true);
CREATE POLICY "Proteccion Lectura Transacciones Logueadas" ON public.transactions FOR ALL TO authenticated USING (true);
